name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang libgl1-mesa-dev libglfw3-dev libglew-dev libassimp-dev
      - name: Build
        env:
          CC: clang
        run: |
          make -j$(nproc)
